Fix issues in clever-tools

diff --git a/bin/clever-install-python b/bin/clever-install-python
--- a/bin/clever-install-python
+++ b/bin/clever-install-python
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 package_installed() {
-    dpkg-query -Wf'${db:Status-abbrev}' "${1}" 2>/dev/null | grep -q '^i'
+    # dpkg-query -Wf'${db:Status-abbrev}' "${1}" 2>/dev/null | grep -q '^i'
+    dpkg-query -Wf'${Status}' "${1}" 2>/dev/null | grep -q '^i'
 }
 
 print_package() {
@@ -15,14 +16,22 @@ print_package() {
 }
 
 packages=( "build-essential" "libssl-dev" "zlib1g-dev" "libmysqlclient-dev" "python-dev" "libjpeg8-dev" "libpng12-dev" )
-
+all_packages=true
 echo -e "Install this packages before continue: "
 for i in "${packages[@]}"
 do
     :
     has_package=`print_package "${i}"`
     printf "                       \E[033;34m         %-20s %b \E[033;39m\n" "${i}" "${has_package}"
+
+    if ! package_installed "${i}"; then
+        all_packages=false
+    fi
 done
+if ! $all_packages; then
+    echo -e "\E[034;31mInstall required packages\E[033;39m"
+    exit 1
+fi
 read -p "Press [Enter] key to start installation or [Ctrl+C]..."
 
 export VENV=$VIRTUAL_ENV
